PrimitiveNames = c("if", "while", "for", "repeat", "break", "next", "return", 
"function", "<-", "=", "<<-", "{", "(", ".subset", ".subset2", 
"[", "[[", "$", "@", "[<-", "[[<-", "$<-", "switch", "browser", 
".primTrace", ".primUntrace", ".Internal", ".Primitive", "call", 
"quote", "substitute", "missing", "nargs", "on.exit", "stop", 
"warning", "gettext", "ngettext", "bindtextdomain", ".addCondHands", 
".resetCondHands", ".signalCondition", ".dfltStop", ".dfltWarn", 
".addRestart", ".getRestart", ".invokeRestart", ".addTryHandlers", 
"geterrmessage", "seterrmessage", "printDeferredWarnings", "interruptsSuspended", 
"restart", "as.function.default", "debug", "undebug", "isdebugged", 
"debugonce", "Recall", "delayedAssign", "makeLazy", "identical", 
"+", "-", "*", "/", "^", "%%", "%/%", "%*%", "==", "!=", "<", 
"<=", ">=", ">", "&", "|", "!", "&&", "||", ":", "~", "all", 
"any", "length", "length<-", "c", "oldClass", "oldClass<-", "class", 
".cache_class", "class<-", "unclass", "names", "names<-", "dimnames", 
"dimnames<-", "dim", "dim<-", "attributes", "attributes<-", "attr", 
"attr<-", "@<-", "levels<-", "vector", "complex", "matrix", "array", 
"diag", "backsolve", "max.col", "row", "col", "unlist", "cbind", 
"rbind", "drop", "all.names", "comment", "comment<-", "get", 
"mget", "exists", "assign", "list2env", "remove", "duplicated", 
"unique", "anyDuplicated", "which", "which.min", "pmin", "pmax", 
"which.max", "match", "pmatch", "charmatch", "match.call", "crossprod", 
"tcrossprod", "attach", "detach", "search", "setFileTime", "round", 
"signif", "log", "log10", "log2", "abs", "floor", "ceiling", 
"sqrt", "sign", "trunc", "exp", "expm1", "log1p", "cos", "sin", 
"tan", "acos", "asin", "atan", "cosh", "sinh", "tanh", "acosh", 
"asinh", "atanh", "lgamma", "gamma", "digamma", "trigamma", "atan2", 
"lbeta", "beta", "lchoose", "choose", "dchisq", "pchisq", "qchisq", 
"dexp", "pexp", "qexp", "dgeom", "pgeom", "qgeom", "dpois", "ppois", 
"qpois", "dt", "pt", "qt", "dsignrank", "psignrank", "qsignrank", 
"besselJ", "besselY", "psigamma", "Re", "Im", "Mod", "Arg", "Conj", 
"dbeta", "pbeta", "qbeta", "dbinom", "pbinom", "qbinom", "dcauchy", 
"pcauchy", "qcauchy", "df", "pf", "qf", "dgamma", "pgamma", "qgamma", 
"dlnorm", "plnorm", "qlnorm", "dlogis", "plogis", "qlogis", "dnbinom", 
"pnbinom", "qnbinom", "dnorm", "pnorm", "qnorm", "dunif", "punif", 
"qunif", "dweibull", "pweibull", "qweibull", "dnchisq", "pnchisq", 
"qnchisq", "dnt", "pnt", "qnt", "dwilcox", "pwilcox", "qwilcox", 
"besselI", "besselK", "dnbinom_mu", "pnbinom_mu", "qnbinom_mu", 
"dhyper", "phyper", "qhyper", "dnbeta", "pnbeta", "qnbeta", "dnf", 
"pnf", "qnf", "dtukey", "ptukey", "qtukey", "rchisq", "rexp", 
"rgeom", "rpois", "rt", "rsignrank", "rbeta", "rbinom", "rcauchy", 
"rf", "rgamma", "rlnorm", "rlogis", "rnbinom", "rnbinom_mu", 
"rnchisq", "rnorm", "runif", "rweibull", "rwilcox", "rhyper", 
"sample", "sample2", "RNGkind", "set.seed", "sum", "min", "max", 
"prod", "mean", "range", "cumsum", "cumprod", "cummax", "cummin", 
"as.character", "as.integer", "as.double", "as.complex", "as.logical", 
"as.raw", "as.call", "as.environment", "storage.mode<-", "as.vector", 
"paste", "paste0", "file.path", "format", "format.info", "cat", 
"do.call", "nchar", "nzchar", "substr", "substr<-", "strsplit", 
"abbreviate", "make.names", "grep", "grepl", "grepRaw", "sub", 
"gsub", "regexpr", "gregexpr", "regexec", "agrep", "adist", "aregexec", 
"tolower", "toupper", "chartr", "sprintf", "make.unique", "charToRaw", 
"rawToChar", "rawShift", "intToBits", "rawToBits", "packBits", 
"utf8ToInt", "intToUtf8", "encodeString", "iconv", "strtrim", 
"strtoi", "is.null", "is.logical", "is.integer", "is.double", 
"is.complex", "is.character", "is.symbol", "is.environment", 
"is.list", "is.pairlist", "is.expression", "is.raw", "is.object", 
"isS4", "is.numeric", "is.matrix", "is.array", "is.atomic", "is.recursive", 
"is.call", "is.language", "is.function", "is.single", "is.na", 
"is.nan", "is.finite", "is.infinite", "is.vector", "proc.time", 
"gc.time", "withVisible", "expression", "interactive", "invisible", 
"rep", "rep.int", "rep_len", "seq.int", "seq_len", "seq_along", 
"list", "xtfrm", "enc2native", "enc2utf8", "emptyenv", "baseenv", 
"globalenv", "environment<-", "pos.to.env", "eapply", "lapply", 
"vapply", "mapply", ".C", ".Fortran", ".External", ".External2", 
".Call", ".External.graphics", ".Call.graphics", "Version", "machine", 
"commandArgs", "system", "parse", "save", "saveToConn", "load", 
"loadFromConn2", "serializeToConn", "unserializeFromConn", "deparse", 
"dput", "dump", "quit", "readline", "print.default", "print.function", 
"prmatrix", "gc", "gcinfo", "gctorture", "gctorture2", "memory.profile", 
"split", "is.loaded", "recordGraphics", "dyn.load", "dyn.unload", 
"ls", "typeof", "eval", "sys.parent", "sys.call", "sys.frame", 
"sys.nframe", "sys.calls", "sys.frames", "sys.on.exit", "sys.parents", 
"sys.function", "traceback", "browserText", "browserCondition", 
"browserSetDebug", "parent.frame", "sort", "is.unsorted", "psort", 
"qsort", "radixsort", "order", "rank", "scan", "t.default", "aperm", 
"builtins", "args", "formals", "body", "bodyCode", "environment", 
"environmentName", "env2list", "reg.finalizer", "options", "sink", 
"sink.number", "rapply", "islistfactor", "colSums", "colMeans", 
"rowSums", "rowMeans", "tracemem", "retracemem", "untracemem", 
"inspect", "mem.limits", "merge", "capabilities", "capabilitiesX11", 
"new.env", "parent.env", "parent.env<-", "l10n_info", "Cstack_info", 
"file.show", "file.create", "file.remove", "file.rename", "file.append", 
"file.symlink", "file.link", "file.copy", "list.files", "list.dirs", 
"file.exists", "file.choose", "file.info", "file.access", "dir.create", 
"tempfile", "tempdir", "R.home", "date", "Sys.getenv", "Sys.setenv", 
"Sys.unsetenv", "getwd", "setwd", "basename", "dirname", "Sys.chmod", 
"Sys.umask", "Sys.readlink", "Sys.info", "Sys.sleep", "Sys.getlocale", 
"Sys.setlocale", "Sys.localeconv", "path.expand", "Sys.getpid", 
"normalizePath", "Sys.glob", "unlink", "polyroot", "inherits", 
"UseMethod", "NextMethod", "standardGeneric", "Sys.time", "as.POSIXct", 
"as.POSIXlt", "format.POSIXlt", "strptime", "Date2POSIXlt", "POSIXlt2Date", 
"mkCode", "bcClose", "is.builtin.internal", "disassemble", "bcVersion", 
"load.from.file", "save.to.file", "growconst", "putconst", "getconst", 
"enableJIT", "compilePKGS", "setNumMathThreads", "setMaxNumMathThreads", 
"stdin", "stdout", "stderr", "isatty", "readLines", "writeLines", 
"readBin", "writeBin", "readChar", "writeChar", "open", "isOpen", 
"isIncomplete", "isSeekable", "close", "flush", "file", "url", 
"pipe", "fifo", "gzfile", "bzfile", "xzfile", "unz", "seek", 
"truncate", "pushBack", "clearPushBack", "pushBackLength", "rawConnection", 
"rawConnectionValue", "textConnection", "textConnectionValue", 
"socketConnection", "sockSelect", "getConnection", "getAllConnections", 
"summary.connection", "gzcon", "memCompress", "memDecompress", 
"readDCF", "lockEnvironment", "environmentIsLocked", "lockBinding", 
"unlockBinding", "bindingIsLocked", "makeActiveBinding", "bindingIsActive", 
"mkUnbound", "isNamespaceEnv", "registerNamespace", "unregisterNamespace", 
"getRegisteredNamespace", "getNamespaceRegistry", "importIntoEnv", 
"env.profile", "Encoding", "setEncoding", "setTimeLimit", "setSessionTimeLimit", 
"icuSetCollate", "readRenviron", "shortRowNames", "copyDFattr", 
"getRegisteredRoutines", "getLoadedDLLs", "getSymbolInfo", ".isMethodsDispatchOn", 
"lazyLoadDBfetch", "lazyLoadDBflush", "getVarsFromFrame", "lazyLoadDBinsertValue", 
"bincode", "tabulate", "findInterval", "pretty", "formatC", "crc64", 
"bitwiseAnd", "bitwiseNot", "bitwiseOr", "bitwiseXor", "bitwiseShiftL", 
"bitwiseShiftR", "serialize", "serializeb", "unserialize", "rowsum_matrix", 
"rowsum_df", "setS4Object", "traceOnOff", "La_qr_cmplx", "La_rs", 
"La_rs_cmplx", "La_rg", "La_rg_cmplx", "La_rs", "La_rs_cmplx", 
"La_dlange", "La_dgecon", "La_dtrcon", "La_zgecon", "La_ztrcon", 
"La_solve_cmplx", "La_solve", "La_qr", "La_chol", "La_chol2inv", 
"qr_coef_real", "qr_qy_real", "det_ge_real", "qr_coef_cmplx", 
"qr_qy_cmpl", "La_svd", "La_svd_cmplx")
